manifest:
  bucket: <your-bucket-name>
  key: <your-key-name>
  url_column: <your-url-key-name>
  status_column: <your-status-key-name>
data_files:
  bucket: <OPTIONAL:your-data-bucket-name>
  suffix: <OPTIONAL:your-suffix>
status_map:
  - status_value_1:
      kf_registered: True
      kf_released: True
  - status_value_2:
      kf_registered: True
      kf_released: False
boto:
  profile_name: <optional:your-aws-profile-name>
