from prefect import flow, task
import sys
import os
import pandas as pd
import json
import uuid
import hashlib
from src.utils import get_logger, get_time, get_date, CheckCCDI
from meval import Validator
from bento_mdf import MDFReader
sys.path.insert(0, os.path.abspath("./prefect-toolkit"))
from workflow.validate_submission import download_model_files

@flow(name="validate record with meval",
    log_prints=True,
    flow_run_name="meval_validation_" + f"{get_time()}",
)
def validate_submission_meval(manifest_filepath: str, data_yml: str, props_yml: str, model_handle:str = "dcc") -> str:
    """This flow parses the manifest into a set of tsv and validate the records using meval Validator class
    This workflow serves as an extra guardrail to ensure the integrity of the records because Validator reads the records in the same way as the meval Loader

    Args:
        manifest_filepath (str): Manifest file path containing the records to be validated.
        data_yml (str): Path to the data YAML file containing the schema for the records.
        props_yml (str): Path to the properties YAML file containing additional validation rules.

    Returns:
        str: file path of the validation report generated by the meval Validator.
    """
    print("Start validating submission records with MEVAL")
    # create validator instance
    model_mdf = MDFReader(data_yml, props_yml, handle=model_handle)
    validator = Validator(mdf=model_mdf)

    # Parse the manifest into a set of tsv files
    # create folder to store parsed tsv files
    tsv_folder = "parsed_tsv_wo_guid"
    os.makedirs(tsv_folder, exist_ok=True)
    check_dcc = CheckCCDI(ccdi_manifest=manifest_filepath)
    # Read in Dictionary page to obtain the required properties
    dict_df = check_dcc.get_dict_df()
    dict_nodes = dict_df["Node"].unique()
    for node in dict_nodes:
        df = check_dcc.read_sheet_na(sheetname=node)
        # check if the dataframe is empty, or only one value under type column, and the rest of the columns are all empty
        if df.empty or df.drop(columns=["type"]).isnull().all().all():
            continue

        # save the df into tsv
        tsv_filepath = os.path.join(tsv_folder, f"{node}_wo_guid.tsv")
        df.to_csv(tsv_filepath, sep="\t", index=False)


    # get the filelist inside the tsv folder
    tsv_filelist = [os.path.join(tsv_folder, f) for f in os.listdir(tsv_folder) if f.endswith(".tsv")]
    print("Number of TSV files to be validated: ", len(tsv_filelist))

    # validate each tsv file using the meval Validator
    record_val = {}
    for tsv_file in tsv_filelist:
        print(f"Validating {tsv_file}")
        tsv_val = validator.validate_tsv_records(
            file_path=tsv_file, subgraph_col=None, id_field=None, delimiter=";" # dcc model used ; as delimiter for list type property
        )
        if len(tsv_val) == 0:
            print(f"All records in file {tsv_file} passed record validation.")
        else:
            print(f"Some records in file {tsv_file} failed validation according to model definition.")
        record_val[tsv_file] = tsv_val

    # write record_val into a file
    record_val_filename = f"meval_validation_results_{get_time()}.json"
    with open(record_val_filename, "w") as f:
        json.dump(record_val, f, indent=4)
    return record_val_filename